version: '3.8'

services:
  # Трекер вакансий
  hh-tracker:
    build: .
    container_name: hh-vacancy-tracker
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command: ["python", "main.py"]
