"""Core модуль приложения."""

from .config import (
    TELEGRAM_BOT_TOKEN,
    TELEGRAM_CHAT_ID,
    ALLOWED_CHAT_IDS,
    EMAIL_ENABLED,
    EMAIL_HOST,
    EMAIL_PORT,
    EMAIL_USER,
    EMAIL_PASSWORD,
    EMAIL_RECIPIENT,
    HH_SEARCH_TEXT,
    HH_AREA,
    HH_SALARY_FROM,
    HH_EMPLOYMENT,
    HH_EXPERIENCE,
    HH_EXCLUDE_WORDS,
    CHECK_INTERVAL,
    DB_PATH,
    DATA_DIR,
    LOG_LEVEL,
    LOG_FILE,
    LOG_MAX_BYTES,
    LOG_BACKUP_COUNT,
    WEB_HOST,
    WEB_PORT,
    BOT_RATE_LIMIT,
    BOT_RATE_WINDOW,
)
from .exceptions import (
    AppError,
    ConfigError,
    DatabaseError,
    ParserError,
    NotificationError,
    VacancyNotFoundError,
    UnauthorizedError,
    RateLimitError,
)
from .logger import setup_logging, get_logger


__all__ = [
    # Config
    'TELEGRAM_BOT_TOKEN',
    'TELEGRAM_CHAT_ID',
    'ALLOWED_CHAT_IDS',
    'EMAIL_ENABLED',
    'EMAIL_HOST',
    'EMAIL_PORT',
    'EMAIL_USER',
    'EMAIL_PASSWORD',
    'EMAIL_RECIPIENT',
    'HH_SEARCH_TEXT',
    'HH_AREA',
    'HH_SALARY_FROM',
    'HH_EMPLOYMENT',
    'HH_EXPERIENCE',
    'HH_EXCLUDE_WORDS',
    'CHECK_INTERVAL',
    'DB_PATH',
    'DATA_DIR',
    'LOG_LEVEL',
    'LOG_FILE',
    'LOG_MAX_BYTES',
    'LOG_BACKUP_COUNT',
    'WEB_HOST',
    'WEB_PORT',
    'BOT_RATE_LIMIT',
    'BOT_RATE_WINDOW',
    # Exceptions
    'AppError',
    'ConfigError',
    'DatabaseError',
    'ParserError',
    'NotificationError',
    'VacancyNotFoundError',
    'UnauthorizedError',
    'RateLimitError',
    # Logger
    'setup_logging',
    'get_logger',
]
